
[window]
width = 1280
height = 720
title = "Test Window"
vsync = true

[particle]
initial_count = 100000
max_count = 1000000
base_size = 2.0

[camera]
initial_mode = "invalid_mode"
orbit_distance = 100.0

[time]
time_acceleration_min = 1.0
time_acceleration_max = 1000000000000.0

[display]
show_fps = true
show_particle_count = true
